Update client.py for python3
gtaylor/petfinder-api pull request #2
Opened 2017-05-23 02:46 UTC by MichaelStadtmiller

the package was breaking for me on line 182. The fix seemed to be adding parens to a print statement on line 182

2017-05-25 15:35 UTC, gtaylor requested changes
Thanks for sending this in! One minor style nit. If you can fix then squash, I'll get this merged.

2017-05-25 15:35 UTC, gtaylor commented on petfinder/client.py
> +                print ("SKIPPING %s") % field
Looks like there's a space between print and the opening parenthesis. I'd also prefer that the substitution happen within the parens:
```
print ("SKIPPING %s" % field )
```

2017-05-25 17:55 UTC, MichaelStadtmiller commented
OK thanks I made the changes and committed.

2017-06-01 15:55 UTC, merged

2017-06-01 15:55 UTC, gtaylor commented
Thanks!